export interface CapabilityEntry {
  id: string;
  status: "supported" | "partial" | "unavailable";
  operations: string[];
  constraints: string[];
}

const feature = (
  id: string,
  status: CapabilityEntry["status"],
  operations: string[],
  ...constraints: string[]
): CapabilityEntry => ({ id, status, operations, constraints });

/** Fresh detached entries on each call; this catalog performs no environment probes. */
export function capabilityCatalog(): CapabilityEntry[] {
  return [
    feature(
      "project.configuration",
      "supported",
      ["StoryboardProject.configure"],
      "Explicit frame-rate timing policy; project seed is retained but not consumed globally by rendering",
    ),
    feature(
      "agent.discovery",
      "supported",
      ["capabilities", "production.query", "ProjectStore.query"],
      "Query default 50, maximum 200; metadata response maximum 256 KiB",
    ),
    feature(
      "agent.edit-plans",
      "partial",
      ["StoryboardProject.plan", "StoryboardProject.commit"],
      "1 MiB JSON; 1–1000 commands; saved base required; request IDs persist receipts",
      "Large raster plan payloads are not externalized",
    ),
    feature(
      "storyboard",
      "supported",
      ["addSequence", "addScene", "scene.addShot", "shot.addPanel", "production.setPanelDuration"],
      "Panels occupy one contiguous global frame timeline",
    ),
    feature(
      "drawing",
      "supported",
      [
        "LayerHandle.rasterStroke",
        "LayerHandle.vectorStroke",
        "LayerHandle.path",
        "LayerHandle.editPixels",
        "production.setDrawingSequence",
      ],
      "Raster surfaces use RGBA8; drawing alternatives are group children; layer.drawing.range edits shot-local holds and restores their end-boundary exposure",
    ),
    feature(
      "animation.curves",
      "supported",
      [
        "production.addLayerKeyframe",
        "production.addCameraKeyframe",
        "StoryboardProject.editShotAnimation",
      ],
      "Sparse channels, holds and easing; board frames are global, shot frames local; layer.pose bakes weighted replacement or numeric additive channel values into ordinary keys",
    ),
    feature(
      "animation.coordinates",
      "supported",
      [
        "production.coordinates",
        "StoryboardProject.shotCoordinates",
        "shotCoordinates",
        "shotPointCoordinates",
      ],
      "Affine local/parent transforms reject mesh ancestry; unstable affine inverse is null. Shot point queries traverse meshes and return all bounded face candidates; unsafe inverses reject. Signed local frames; geometry only, no visibility filtering; mesh/render parity awaits runtime qualification",
    ),
    feature(
      "timing.rational",
      "partial",
      ["normalizeRate", "rescaleTime"],
      "Exact intermediate tick conversion with explicit rounding; project retiming and movie sample placement use the mapper",
      "Board project rates remain numbers; audio source positions remain frames; no drop-frame timecode",
    ),
    feature(
      "animation.shot-retime",
      "partial",
      ["retimeShotAnimation", "StoryboardProject.editShotAnimation"],
      "Detached duration-ratio preview and timing.retime edit cover camera, layers, drawings, reveal, controllers, deformers and compositing; explicit rounding rejects collisions; audio cue starts preserve seconds or scale by physical duration",
      "No audio sample stretching or automatic editorial cut conform; runtime timing, persistence and playback qualification pending",
    ),
    feature(
      "animation.rigging",
      "partial",
      [
        "production.setTwoBoneRig",
        "production.poseTwoBoneRig",
        "shotMeshData",
        "shotControllerData",
        "captureShotController",
        "createControllerPerformance",
        "compileControllerPerformance",
        "StoryboardProject.editShotAnimation",
      ],
      "Two-bone IK and persisted rest-pose capture/apply; explicit reject/clamp reach policy. layer.mesh authors vertex deformation; layer.curve stores a cubic ribbon; layer.envelope stores a four-boundary Coons patch. layer.skin binds explicit weights to animated joint layers; named controllers blend numeric layer poses over base keys. Runtime qualification pending; no automatic weights, arbitrary envelope cages, curve chains or full rig/artwork performance packages; numeric controller packages support checksum validation and explicit target mapping",
    ),
    feature(
      "camera",
      "supported",
      ["production.addCameraKeyframe", "production.setPlaneDepth"],
      "2D camera and depth planes; no native 3D scene",
    ),
    feature(
      "audio",
      "partial",
      ["production.addAudioClip", "production.splitAudioClip", "exportMovie"],
      "Placement and trimming use project frames; movie audio is resampled to 48 kHz",
      "No persisted sample-accurate source positions, automatic alignment or mouth mapping",
    ),
    feature(
      "audio.studio",
      "partial",
      [
        "defineStudioAudio",
        "compileStudioAudio",
        "conformShotAudio",
        "conformEditorialAudio",
        "mixShotAudio",
        "mixEditorialAudio",
        "exportAudioStems",
        "verifyAudioStems",
        "parseAudioStemManifest",
        "createFFmpegAudioDecoder",
        "StoryboardProject.setStudioAudio",
        "StoryboardProject.editStudioAudio",
        "reviseStudioAudio",
      ],
      "Persisted shot/editorial tracks use source samples and rational placement; nearest conversion reports quantization; exact conversion rejects it before decoding",
      "clip.split uses a source-sample offset and explicit new ID; exact rational placement and outer fades are preserved; cuts through fades reject",
      "Source sample-rate metadata is declared, not probed; PCM mixing supports FFmpeg/ffprobe decoding of pipe-readable mono/stereo media; studio movie mixing supports explicit sum/linear policies; conform supports sum or linear overlap; movies require explicit mix/omission when studio audio exists",
    ),
    feature(
      "render.jobs",
      "partial",
      [
        "createFrameJob",
        "runFrameJob",
        "inspectFrameJob",
        "readFrameJobFrame",
        "exportFrameJobMovie",
        "exportFrameJobSequence",
        "verifyFrameSequence",
        "verifyFrameJob",
        "inspectProjectFonts",
        "inspectShotFonts",
      ],
      "Saved shot/editorial sources with version/content and engine identity checks; SQLite stores each PNG and checksum atomically; shot targets can pin selected-layer passes and transparent backgrounds; optional immutable 8-bit PNG profiles resize/fit and preserve alpha or flatten against explicit RGB",
      "Resume verifies visited frames; optional require-available font preflight checks every referenced shot on creation and each run; movie export reuses stored PNGs and studio audio policies; source file must remain available; optional checksum-pinned font files are supported; no scheduler, glyph-coverage guarantee or universal cross-platform pixel identity",
    ),
    feature(
      "assets.components",
      "partial",
      [
        "production.captureComponent",
        "production.instantiateComponent",
        "production.refreshComponentInstance",
        "production.replaceComponentElement",
        "production.replaceComponentSource",
        "production.upgradeComponentInstance",
        "StoryboardProject.previewComponentUpgrade",
        "StoryboardProject.componentOriginData",
        "planComponentSource",
      ],
      "Static source replacement retains explicit IDs; tracked board/shot instances retain baselines and support hash-guarded three-way upgrades with conflict resolutions and explicit new-object mappings",
      "Refresh remains destructive replacement with comment policy; legacy untracked instances cannot upgrade; no inferred topology correspondence or full production qualification",
    ),
    feature(
      "review",
      "partial",
      [
        "exportReview",
        "readReviewManifest",
        "verifyReviewExport",
        "createReviewDecision",
        "readReviewDecision",
        "verifyReviewDecision",
        "renderContactSheet",
        "renderFrameSheet",
        "renderDetail",
        "renderOnionSkin",
        "comparePixels",
      ],
      "Saved-snapshot board/shot/editorial frame manifests with source-frame mapping; maximum 120 frames and 128 MiB PNG data",
      "Review packages support hash/decode checks and portable checksummed decisions bound to manifest/source/frame identities; caller supplies reviewer, outcome and criteria; unsigned decisions are not authenticated or automatically artistic approval, and do not update project status",
    ),
    feature(
      "persistence",
      "supported",
      [
        "StoryboardProject.save",
        "ProjectStore.saveRevision",
        "ProjectStore.restoreRevision",
        "ProjectStore.compact",
        "ProjectStore.copyTo",
        "publishProject",
        "verifyProjectPublish",
        "exportShotProject",
        "StoryboardProject.shotDependencyData",
      ],
      "SQLite atomic writes and optimistic versions; actor locks coordinate edits and are not authentication",
      "Full-container publish retains history/media; single-shot native export selects component/origin/palette/media dependencies and starts independent history. Pinned source, new project ID, 1 GiB maximum and no overwrite; external fonts remain declarations; cross-project resource/ID import and handoff runtime qualification remain incomplete",
    ),
    feature(
      "delivery.movie",
      "partial",
      ["exportMovie", "exportShotMovie", "exportEditorialMovie"],
      "Requires FFmpeg and compatible encoders; even dimensions and matching panel sizes; optional require-available font preflight runs before audio decoding/rendering",
      "Studio mix uses stereo 48 kHz PCM/AAC, rejects clipping and is limited to 16777216 samples; persistent PNG jobs are a separate workflow; font availability does not lock font binaries or guarantee glyph coverage",
    ),
    feature(
      "editorial.shot-local",
      "partial",
      [
        "StoryboardProject.setStudio",
        "StoryboardProject.capturePanelAnimation",
        "StoryboardProject.boardPanels",
        "planBoardCapture",
        "StoryboardProject.duplicateShotAnimation",
        "StoryboardProject.shotBoardPanels",
        "StoryboardProject.putShotAnimation",
        "StoryboardProject.editShotAnimation",
        "reviseShotAnimation",
        "StoryboardProject.putEditorialSequence",
        "StoryboardProject.editEditorial",
        "reviseEditorialSequence",
        "StoryboardProject.addShotElement",
        "StoryboardProject.removeShotElements",
        "StoryboardProject.reviseShotElement",
        "StoryboardProject.patchShotPixels",
        "planShotAnimation",
        "mergeShotAnimation",
        "planShotMerge",
        "planShotHandoffMerge",
        "defineShotAnimation",
        "defineEditorialSequence",
        "resolveEditorialFrame",
        "createEditorialResolver",
        "createShotRenderSession",
        "createEditorialRenderSession",
        "renderShotFramePNG",
        "renderEditorialFramePNG",
      ],
      "Persisted studio payloads/checkpoints with shot-local artwork, rational-rate editorial clips and explicit initial picture holds; shot audio starts after the hold while sequence audio remains independent",
      "Three-way shot merge preserves independent local fields; native handoff adapter checks baseline provenance and resource compatibility. Whole-shot duplication remaps owned rig/controller/audio identities. Structure/retiming conflicts require explicit choices; no automatic dependency import or full production qualification",
      "Per-animation/sequence plans and bounded element/pixel edits; panel capture preserves local curves with remapped identities and explicit pre/post-roll handles; full-board plans use incoming holds and explicit audio conversion/omission; picture/audio/persistence qualification pending",
    ),
    feature(
      "project.migration",
      "partial",
      ["migrateProject"],
      "Schema-3/4 containers are read-only; migrate the current document/media to a new schema-5, container-3 destination",
      "Board timing/IDs are retained; studio starts empty for schema-3 input and is retained for schema-4; checkpoints/receipts remain in the original; older readers reject the new container rather than dropping effects",
    ),
    feature(
      "palettes",
      "partial",
      [
        "StoryboardProject.putPalette",
        "StoryboardProject.setColorBinding",
        "StoryboardProject.paletteSwatches",
        "StoryboardProject.paletteBindings",
        "StoryboardProject.removePalette",
        "mergePalette",
        "planPaletteMerge",
      ],
      "Shared solid-color swatches propagate to bound artwork with local overrides; three-way palette merge prepares native plans with explicit value/structure conflicts; reference preflight precedes mutation",
      "No gradient-stop or pixel recoloring, scoped palette variants, external palette publishing or managed color-space conversion",
    ),
    feature(
      "story.caption-import",
      "partial",
      ["parseCaptionCSV", "planCaptionImport", "StoryboardProject.panelCaptions"],
      "Strict CSV or typed rows target stable panel IDs and produce field-level differences plus an atomic caption-only edit plan",
      "Existing panels only; no inferred matching or new-panel creation; use script import for Final Draft records",
    ),
    feature(
      "story.script",
      "partial",
      [
        "StoryboardProject.replaceScript",
        "StoryboardProject.scriptSummary",
        "StoryboardProject.scriptEntries",
        "planScriptBoard",
        "importScriptCSV",
        "exportScriptCSV",
        "inspectScriptFDX",
        "importScriptFDX",
      ],
      "Persisted scene/action/dialogue records with stable IDs, revision-checked replacement, field-change reports, ordered panel links and script.replace plans",
      "One script per project; explicit IDs, shot staging and durations; FDX v3 scene/action/dialogue subset with hash-bound mappings and loss reports; board plans create empty panels and links, not artwork; no automatic regeneration",
    ),
    feature(
      "compositing.effects",
      "partial",
      ["LayerHandle.set", "production.reparentLayer", "renderShotFramePNG"],
      "Blend modes, clipping, masks, mesh surfaces and persisted ordered layer/group effects: brightness, contrast, saturation, hue rotation, Gaussian blur and colored drop shadows with keyed blur/offset/opacity",
      "Effects use separate ordered passes on the 8-bit Canvas backend after layer mask and before sibling clipping/opacity/blend; at most 16 effects per layer and 64 indexed channel values per key; blur/shadow margins crop back and reject effective blur above 512 pixels, shadow offsets above 4096 pixels and expanded surfaces above 32 megapixels; shadow RGB is static; mesh triangle coverage is unchanged; no OCIO pipeline; CPU mesh coverage is capped at 268435456 sample tests per warp; effect pixel qualification pending",
    ),
    feature(
      "compositing.graph",
      "partial",
      ["createShotRenderSession", "renderShotFramePNG", "createFrameJob"],
      "Typed source/effects/blend/alpha-mask DAG stored on shots through compositing.set, inherited by editorial rendering, or overridden in shot render options; source/job identity pins effective configuration; duplication remaps source layers",
      "32 nodes, 32 KiB graph including curves and 256 megapixel-passes per frame; effect values and blend opacity have shot-local eased keys; explicit layer sources and one reachable output; ports are cropped post-camera RGBA frames; topology/modes/RGB static; no separate editorial-level graph; runtime pixel/seek/job/duplication qualification pending",
    ),
    feature(
      "interchange.otio",
      "partial",
      ["importOTIO", "exportOTIO"],
      "One video cut track, explicit external-media bindings, source origins and exact rate conversion; Clip.1/Clip.2 import and Clip.2 export; no media reads or artwork embedding",
      "1 MiB JSON and 1000 clips; unrepresented names/metadata/audio require explicit report policy; effects, transitions, gaps, retimes and nested/multiple video tracks are rejected; no NLE application qualification",
    ),
    feature(
      "interchange.psd",
      "partial",
      ["importPSD"],
      "PSD v1 untagged RGB8 pixel layers and isolated groups; explicit sRGB interpretation, Unicode names, opacity, visibility, six mapped blend modes, source-ID namespaces and metadata loss reports",
      "64 MiB input, 256 layer records, 32 megapixels of decoded layers and group depth 16; raw/RLE/bounded ZIP channels; tagged ICC, PSB, clipping, masks, pass-through groups, text, effects, smart objects and unknown blocks reject; merged preview ignored; no PSD export or Photoshop application qualification",
    ),
    feature(
      "animation.lip-sync",
      "partial",
      ["compileLipSync", "rescaleLipSync", "planShotLipSync"],
      "Frame-addressed mouth mappings and explicit manual corrections bake to editable drawing exposures; shot plans preserve surrounding exposures; rational cue/range/correction conversion rejects collapsed intervals",
      "Requires authored mouth drawings and supplied frame cues; no speech recognition, phoneme extraction or automatic acting assessment",
    ),
  ];
}
