import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { author } from "../project/author.ts";
import { output } from "../config.ts";
import { render } from "../review/render.ts";
await mkdir(output, { recursive: true });
const project = await author(output);
await project.save(join(output, "last-light.cboard"), { overwrite: true });
await render(project, output, process.argv.includes("--movie"));
console.log(`Created editable project and review files in ${output}; visual review is pending.`);
