/** Guide associations describe what a picture demonstrates, not test coverage. */
export const studyDocs: Record<string, string[]> = {
  representations: ["drawing/marks", "drawing/pixels"],
  clipping: ["drawing/layers"],
  selections: ["drawing/pixels"],
  palettes: ["drawing/palettes"],
  "color-import": ["drawing/pixels"],
  "perspective-guides": ["animation/camera", "workflow/review"],
  "gradient-fills": ["drawing/marks"],
  "vector-booleans": ["drawing/marks"],
  "brush-dynamics": ["drawing/brushes"],
  "brush-import": ["drawing/import-brushes"],
  "stroke-outline": ["drawing/marks"],
  "layer-order": ["drawing/organizing-layers"],
  masks: ["drawing/layers"],
  "layer-effects": ["drawing/effects"],
  "blend-modes": ["drawing/layers"],
  "onion-skin": ["animation/onion-skins"],
  easing: ["animation/timing"],
  pivots: ["drawing/organizing-layers", "animation/joints"],
  "stroke-reveal": ["animation/timing"],
  "drawing-holds": ["animation/drawing-holds"],
  "camera-framing": ["animation/camera"],
  retiming: ["animation/retiming"],
  transitions: ["animation/editing"],
  envelope: ["animation/envelopes"],
  "skin-weights": ["animation/skinning"],
  "drawing-timing": ["animation/drawing-holds"],
  "weighted-pose": ["animation/poses", "animation/performance-files"],
  "ik-reach": ["drawing/geometry", "animation/rigging"],
  "rig-rest": ["animation/rest-pose"],
  "mesh-warp": ["animation/meshes", "animation/curves"],
  "mesh-alpha": ["animation/meshes"],
  "deformer-resolution": ["animation/meshes"],
  "controller-exchange": ["animation/controllers", "animation/transfer"],
  "lip-sync": ["animation/lip-sync"],
  "camera-depth": ["animation/camera"],
  "editorial-cuts": ["animation/editing", "animation/shots"],
  components: ["drawing/components"],
  "component-upgrade": ["drawing/component-upgrades"],
  "psd-import": ["drawing/pixels"],
  hierarchy: ["animation/storyboards", "animation/board-layout", "start/project-model"],
  "script-board": ["animation/scripts", "animation/script-import", "animation/captions"],
  "motion-notes": ["animation/storyboards"],
  "audio-placement": ["audio/board-audio", "audio/editing", "audio/shot-audio"],
  "audio-delivery": ["audio/mixing", "audio/stems", "delivery/movies"],
  "asset-replacement": ["audio/editing"],
  "saved-revision": ["workflow/review", "workflow/projects"],
  "review-tools": ["workflow/review", "workflow/review-packages"],
  "font-preflight": ["delivery/movies"],
  "frame-jobs": ["delivery/frame-jobs", "delivery/frame-sequences"],
  "render-passes": ["delivery/passes", "delivery/compositing"],
  "output-profiles": ["delivery/passes"],
  migration: ["workflow/migration"],
  "project-publish": ["workflow/handoff"],
  "shot-merge": ["workflow/merging"],
  "otio-conform": ["animation/otio"],
};
