import { basePath, repository } from '@/lib/shared';
export const metadata = { title: 'Examples' };
export default function Examples() {
  return <main className="site-main inner-page"><span className="section-label">Made with the public API</span><h1>Code on one side.<br /><em>A story on the other.</em></h1><p className="page-lead">Original projects you can read, render and revise. The artwork is authored with Codeboard's drawing tools, not imported AI-generated frames.</p>
    <section id="last-light" className="example-project"><div className="project-heading"><h2>The Last Light</h2><span>14 panels · 30.5 seconds</span></div><video controls preload="none" poster={`${basePath}/art/last-light.png`} src={`${basePath}/art/last-light.mp4`} aria-label="The Last Light animatic"><a href={`${basePath}/art/last-light.mp4`}>Download The Last Light video</a></video><p>A lantern keeper lends the last of his light to a broken mechanical firefly. Layered city artwork, frame-by-frame wings, camera motion and an original soundtrack.</p><p className="fine-print">A development example demonstrating the engine. Illustration and acting remain stylized; this is not a claim of full-animation production parity.</p><div className="actions"><a className="button secondary" href={`${repository}/blob/main/examples/last-light.ts`}>Read the authoring source</a><a className="text-link" href={`${repository}/blob/main/examples/revise-last-light.ts`}>Inspect a directed revision</a></div></section>
    <section className="example-project"><div className="project-heading"><h2>Lengkap</h2><span>6 scenes · 15 seconds</span></div><video controls preload="none" poster={`${basePath}/art/lengkap-storyboard.png`} src={`${basePath}/art/lengkap.mp4`} aria-label="Lengkap brush film"><a href={`${basePath}/art/lengkap.mp4`}>Download Lengkap video</a></video><p>A report says everything is there. The warehouse tells a different story. Procedural brushwork, a red approval stamp and original Foley.</p><a className="button secondary" href={`${repository}/blob/main/examples/lengkap.ts`}>Read the authoring source</a></section>
    <p className="fine-print">Example source code: MIT. Original artwork and audio: CC0-1.0.</p>
  </main>;
}
